import { halls } from './halls';

export const schedules = [
  {
    filmId: '1',
    schedule: [
      [
        { time: '10:20', hall: halls.red },
        { time: '14:30', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '20:30', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '17:40', hall: halls.green },
        { time: '20:10', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '22:40', hall: halls.blue }
      ],
      [
        { time: '12:30', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '20:00', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '17:50', hall: halls.green },
        { time: '20:20', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '17:10', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ],
      [
        { time: '12:00', hall: halls.red },
        { time: '15:40', hall: halls.red },
        { time: '16:50', hall: halls.red },
        { time: '20:30', hall: halls.red },
        { time: '10:10', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '17:00', hall: halls.green },
        { time: '22:00', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '17:00', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '14:10', hall: halls.red },
        { time: '18:20', hall: halls.red },
        { time: '21:20', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '13:30', hall: halls.green },
        { time: '18:00', hall: halls.green },
        { time: '20:40', hall: halls.green },
        { time: '12:20', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '17:10', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ],
      [
        { time: '11:50', hall: halls.red },
        { time: '14:50', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '22:20', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '13:30', hall: halls.green },
        { time: '18:10', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '11:10', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '18:30', hall: halls.blue },
        { time: '21:10', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:30', hall: halls.red },
        { time: '12:10', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '18:30', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '17:10', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '10:30', hall: halls.red },
        { time: '14:50', hall: halls.red },
        { time: '16:20', hall: halls.red },
        { time: '21:10', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '15:50', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '20:30', hall: halls.green },
        { time: '11:10', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '18:10', hall: halls.blue },
        { time: '22:00', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '2',
    schedule: [
      [
        { time: '11:10', hall: halls.red },
        { time: '15:30', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:00', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '15:40', hall: halls.green },
        { time: '16:00', hall: halls.green },
        { time: '20:20', hall: halls.green },
        { time: '12:10', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:50', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '12:40', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '17:30', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '10:00', hall: halls.blue },
        { time: '15:50', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '22:50', hall: halls.blue }
      ],
      [
        { time: '11:40', hall: halls.red },
        { time: '13:30', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '20:50', hall: halls.red },
        { time: '12:40', hall: halls.green },
        { time: '13:00', hall: halls.green },
        { time: '16:20', hall: halls.green },
        { time: '20:00', hall: halls.green },
        { time: '11:50', hall: halls.blue },
        { time: '13:00', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '21:50', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:50', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '15:20', hall: halls.green },
        { time: '16:20', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '13:20', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:10', hall: halls.blue }
      ],
      [
        { time: '11:10', hall: halls.red },
        { time: '14:30', hall: halls.red },
        { time: '16:50', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '18:30', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:50', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:00', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:20', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '13:00', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '21:10', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '22:40', hall: halls.blue }
      ],
      [
        { time: '10:10', hall: halls.red },
        { time: '14:10', hall: halls.red },
        { time: '18:30', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '18:40', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '12:20', hall: halls.blue },
        { time: '15:50', hall: halls.blue },
        { time: '17:00', hall: halls.blue },
        { time: '22:00', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '3',
    schedule: [
      [
        { time: '10:40', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '17:30', hall: halls.red },
        { time: '20:40', hall: halls.red },
        { time: '11:40', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '18:10', hall: halls.green },
        { time: '22:40', hall: halls.green },
        { time: '10:10', hall: halls.blue },
        { time: '13:20', hall: halls.blue },
        { time: '18:20', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '14:40', hall: halls.red },
        { time: '18:50', hall: halls.red },
        { time: '21:20', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '13:10', hall: halls.green },
        { time: '17:30', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '10:00', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '16:00', hall: halls.blue },
        { time: '20:40', hall: halls.blue }
      ],
      [
        { time: '10:10', hall: halls.red },
        { time: '13:40', hall: halls.red },
        { time: '16:40', hall: halls.red },
        { time: '20:00', hall: halls.red },
        { time: '11:10', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '16:30', hall: halls.green },
        { time: '21:10', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '17:30', hall: halls.blue },
        { time: '20:30', hall: halls.blue }
      ],
      [
        { time: '10:40', hall: halls.red },
        { time: '13:50', hall: halls.red },
        { time: '16:30', hall: halls.red },
        { time: '22:40', hall: halls.red },
        { time: '12:40', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '17:20', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '14:30', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '20:10', hall: halls.blue }
      ],
      [
        { time: '11:30', hall: halls.red },
        { time: '13:00', hall: halls.red },
        { time: '16:40', hall: halls.red },
        { time: '21:20', hall: halls.red },
        { time: '10:40', hall: halls.green },
        { time: '13:50', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '11:50', hall: halls.blue },
        { time: '15:00', hall: halls.blue },
        { time: '16:30', hall: halls.blue },
        { time: '21:20', hall: halls.blue }
      ],
      [
        { time: '10:20', hall: halls.red },
        { time: '13:40', hall: halls.red },
        { time: '18:50', hall: halls.red },
        { time: '21:10', hall: halls.red },
        { time: '11:40', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '17:30', hall: halls.green },
        { time: '22:00', hall: halls.green },
        { time: '12:00', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '18:40', hall: halls.blue },
        { time: '21:00', hall: halls.blue }
      ],
      [
        { time: '10:40', hall: halls.red },
        { time: '14:00', hall: halls.red },
        { time: '16:40', hall: halls.red },
        { time: '21:40', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '16:20', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '11:40', hall: halls.blue },
        { time: '15:30', hall: halls.blue },
        { time: '16:40', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '4',
    schedule: [
      [
        { time: '10:10', hall: halls.red },
        { time: '15:30', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '20:00', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '18:50', hall: halls.green },
        { time: '22:40', hall: halls.green },
        { time: '12:10', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '17:10', hall: halls.blue },
        { time: '22:40', hall: halls.blue }
      ],
      [
        { time: '11:20', hall: halls.red },
        { time: '14:30', hall: halls.red },
        { time: '17:20', hall: halls.red },
        { time: '22:20', hall: halls.red },
        { time: '10:10', hall: halls.green },
        { time: '13:00', hall: halls.green },
        { time: '18:10', hall: halls.green },
        { time: '20:30', hall: halls.green },
        { time: '12:20', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '22:30', hall: halls.blue }
      ],
      [
        { time: '10:00', hall: halls.red },
        { time: '15:00', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '20:40', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '18:50', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:50', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '21:10', hall: halls.blue }
      ],
      [
        { time: '12:00', hall: halls.red },
        { time: '13:40', hall: halls.red },
        { time: '17:30', hall: halls.red },
        { time: '21:10', hall: halls.red },
        { time: '12:10', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '16:30', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '12:30', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '18:50', hall: halls.blue },
        { time: '20:20', hall: halls.blue }
      ],
      [
        { time: '12:20', hall: halls.red },
        { time: '14:40', hall: halls.red },
        { time: '16:30', hall: halls.red },
        { time: '20:50', hall: halls.red },
        { time: '11:10', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '20:20', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '18:30', hall: halls.blue },
        { time: '22:40', hall: halls.blue }
      ],
      [
        { time: '11:50', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '16:10', hall: halls.red },
        { time: '21:20', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '15:20', hall: halls.green },
        { time: '16:10', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '12:30', hall: halls.blue },
        { time: '13:50', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '22:10', hall: halls.blue }
      ],
      [
        { time: '11:40', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '16:50', hall: halls.red },
        { time: '21:40', hall: halls.red },
        { time: '10:40', hall: halls.green },
        { time: '15:40', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '10:00', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '17:10', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '5',
    schedule: [
      [
        { time: '10:30', hall: halls.red },
        { time: '15:40', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '21:20', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '13:40', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '21:10', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:50', hall: halls.blue }
      ],
      [
        { time: '12:50', hall: halls.red },
        { time: '15:30', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '11:40', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '18:30', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '12:00', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ],
      [
        { time: '11:10', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '16:10', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '10:10', hall: halls.green },
        { time: '13:30', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '22:40', hall: halls.green },
        { time: '11:30', hall: halls.blue },
        { time: '14:10', hall: halls.blue },
        { time: '16:40', hall: halls.blue },
        { time: '20:00', hall: halls.blue }
      ],
      [
        { time: '12:50', hall: halls.red },
        { time: '15:30', hall: halls.red },
        { time: '17:50', hall: halls.red },
        { time: '20:40', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '17:40', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '10:00', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '18:20', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '13:20', hall: halls.red },
        { time: '16:50', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '15:50', hall: halls.green },
        { time: '18:40', hall: halls.green },
        { time: '22:30', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '14:10', hall: halls.blue },
        { time: '17:40', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ],
      [
        { time: '12:50', hall: halls.red },
        { time: '14:30', hall: halls.red },
        { time: '16:20', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '12:40', hall: halls.blue },
        { time: '13:20', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '20:20', hall: halls.blue }
      ],
      [
        { time: '10:30', hall: halls.red },
        { time: '13:20', hall: halls.red },
        { time: '18:40', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '15:40', hall: halls.green },
        { time: '18:20', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '18:50', hall: halls.blue },
        { time: '21:10', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '6',
    schedule: [
      [
        { time: '12:50', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '18:30', hall: halls.red },
        { time: '22:40', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '13:30', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '22:00', hall: halls.blue }
      ],
      [
        { time: '11:20', hall: halls.red },
        { time: '15:00', hall: halls.red },
        { time: '17:20', hall: halls.red },
        { time: '21:10', hall: halls.red },
        { time: '12:20', hall: halls.green },
        { time: '14:30', hall: halls.green },
        { time: '17:40', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '11:50', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '21:20', hall: halls.blue }
      ],
      [
        { time: '10:00', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:20', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '13:10', hall: halls.green },
        { time: '18:40', hall: halls.green },
        { time: '21:30', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '14:10', hall: halls.blue },
        { time: '16:00', hall: halls.blue },
        { time: '22:50', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:30', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '18:20', hall: halls.blue },
        { time: '21:10', hall: halls.blue }
      ],
      [
        { time: '11:00', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '18:30', hall: halls.red },
        { time: '21:30', hall: halls.red },
        { time: '12:50', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '17:20', hall: halls.green },
        { time: '20:40', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '14:30', hall: halls.blue },
        { time: '18:10', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '22:20', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '21:30', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '18:30', hall: halls.blue },
        { time: '20:00', hall: halls.blue }
      ],
      [
        { time: '11:00', hall: halls.red },
        { time: '14:00', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '10:30', hall: halls.green },
        { time: '14:40', hall: halls.green },
        { time: '18:40', hall: halls.green },
        { time: '21:40', hall: halls.green },
        { time: '12:30', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '20:00', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '7',
    schedule: [
      [
        { time: '11:00', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '16:40', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '12:00', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '10:30', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '13:30', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '11:40', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '16:10', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '15:30', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '21:50', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '12:30', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '16:30', hall: halls.green },
        { time: '22:00', hall: halls.green },
        { time: '11:50', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '18:00', hall: halls.blue },
        { time: '20:20', hall: halls.blue }
      ],
      [
        { time: '12:30', hall: halls.red },
        { time: '15:00', hall: halls.red },
        { time: '17:30', hall: halls.red },
        { time: '20:40', hall: halls.red },
        { time: '11:40', hall: halls.green },
        { time: '15:20', hall: halls.green },
        { time: '18:30', hall: halls.green },
        { time: '21:40', hall: halls.green },
        { time: '10:10', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '18:10', hall: halls.blue },
        { time: '21:30', hall: halls.blue }
      ],
      [
        { time: '11:10', hall: halls.red },
        { time: '15:10', hall: halls.red },
        { time: '16:20', hall: halls.red },
        { time: '20:50', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '17:40', hall: halls.green },
        { time: '20:40', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:10', hall: halls.red },
        { time: '16:30', hall: halls.red },
        { time: '20:30', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:10', hall: halls.green },
        { time: '16:10', hall: halls.green },
        { time: '20:20', hall: halls.green },
        { time: '10:30', hall: halls.blue },
        { time: '15:40', hall: halls.blue },
        { time: '17:40', hall: halls.blue },
        { time: '21:30', hall: halls.blue }
      ],
      [
        { time: '11:40', hall: halls.red },
        { time: '13:50', hall: halls.red },
        { time: '18:00', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:10', hall: halls.green },
        { time: '17:10', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '11:00', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '8',
    schedule: [
      [
        { time: '12:40', hall: halls.red },
        { time: '14:40', hall: halls.red },
        { time: '18:10', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '12:10', hall: halls.green },
        { time: '13:40', hall: halls.green },
        { time: '17:50', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '10:10', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '22:40', hall: halls.blue }
      ],
      [
        { time: '12:30', hall: halls.red },
        { time: '14:10', hall: halls.red },
        { time: '18:30', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:30', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '22:10', hall: halls.blue }
      ],
      [
        { time: '11:10', hall: halls.red },
        { time: '14:10', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '14:20', hall: halls.green },
        { time: '17:50', hall: halls.green },
        { time: '20:10', hall: halls.green },
        { time: '12:10', hall: halls.blue },
        { time: '14:20', hall: halls.blue },
        { time: '18:20', hall: halls.blue },
        { time: '22:50', hall: halls.blue }
      ],
      [
        { time: '10:40', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '18:20', hall: halls.red },
        { time: '21:30', hall: halls.red },
        { time: '12:00', hall: halls.green },
        { time: '14:10', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '20:20', hall: halls.green },
        { time: '11:20', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '16:30', hall: halls.blue },
        { time: '20:50', hall: halls.blue }
      ],
      [
        { time: '12:40', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '17:30', hall: halls.red },
        { time: '20:10', hall: halls.red },
        { time: '10:10', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '12:40', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '18:50', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:00', hall: halls.red },
        { time: '16:40', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '10:40', hall: halls.green },
        { time: '15:40', hall: halls.green },
        { time: '17:40', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '10:10', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '18:50', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ],
      [
        { time: '12:10', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '16:20', hall: halls.red },
        { time: '22:20', hall: halls.red },
        { time: '11:20', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '17:30', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '11:40', hall: halls.blue },
        { time: '14:30', hall: halls.blue },
        { time: '16:30', hall: halls.blue },
        { time: '21:40', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '9',
    schedule: [
      [
        { time: '11:50', hall: halls.red },
        { time: '13:10', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '15:30', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '20:50', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '13:50', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '22:10', hall: halls.blue }
      ],
      [
        { time: '11:20', hall: halls.red },
        { time: '15:30', hall: halls.red },
        { time: '17:50', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:50', hall: halls.green },
        { time: '16:10', hall: halls.green },
        { time: '22:20', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '18:50', hall: halls.blue },
        { time: '20:20', hall: halls.blue }
      ],
      [
        { time: '10:50', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '17:40', hall: halls.red },
        { time: '21:00', hall: halls.red },
        { time: '11:10', hall: halls.green },
        { time: '13:10', hall: halls.green },
        { time: '18:50', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '10:30', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '16:10', hall: halls.blue },
        { time: '21:30', hall: halls.blue }
      ],
      [
        { time: '10:20', hall: halls.red },
        { time: '13:50', hall: halls.red },
        { time: '18:50', hall: halls.red },
        { time: '22:40', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '13:20', hall: halls.green },
        { time: '16:10', hall: halls.green },
        { time: '22:50', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '18:30', hall: halls.blue },
        { time: '20:30', hall: halls.blue }
      ],
      [
        { time: '10:30', hall: halls.red },
        { time: '13:40', hall: halls.red },
        { time: '16:20', hall: halls.red },
        { time: '21:40', hall: halls.red },
        { time: '12:40', hall: halls.green },
        { time: '13:30', hall: halls.green },
        { time: '18:00', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '14:50', hall: halls.blue },
        { time: '17:50', hall: halls.blue },
        { time: '20:10', hall: halls.blue }
      ],
      [
        { time: '10:30', hall: halls.red },
        { time: '15:00', hall: halls.red },
        { time: '17:10', hall: halls.red },
        { time: '22:40', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '13:50', hall: halls.green },
        { time: '18:00', hall: halls.green },
        { time: '20:10', hall: halls.green },
        { time: '10:10', hall: halls.blue },
        { time: '13:30', hall: halls.blue },
        { time: '16:20', hall: halls.blue },
        { time: '20:00', hall: halls.blue }
      ],
      [
        { time: '12:30', hall: halls.red },
        { time: '13:00', hall: halls.red },
        { time: '16:50', hall: halls.red },
        { time: '20:00', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '17:00', hall: halls.green },
        { time: '21:50', hall: halls.green },
        { time: '12:20', hall: halls.blue },
        { time: '13:20', hall: halls.blue },
        { time: '16:40', hall: halls.blue },
        { time: '22:50', hall: halls.blue }
      ]
    ]
  },

  {
    filmId: '10',
    schedule: [
      [
        { time: '10:30', hall: halls.red },
        { time: '13:40', hall: halls.red },
        { time: '17:30', hall: halls.red },
        { time: '22:10', hall: halls.red },
        { time: '10:20', hall: halls.green },
        { time: '15:10', hall: halls.green },
        { time: '17:20', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '10:50', hall: halls.blue },
        { time: '14:40', hall: halls.blue },
        { time: '16:40', hall: halls.blue },
        { time: '22:30', hall: halls.blue }
      ],
      [
        { time: '10:20', hall: halls.red },
        { time: '14:40', hall: halls.red },
        { time: '17:50', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '10:40', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '21:20', hall: halls.green },
        { time: '12:50', hall: halls.blue },
        { time: '15:10', hall: halls.blue },
        { time: '17:40', hall: halls.blue },
        { time: '20:40', hall: halls.blue }
      ],
      [
        { time: '11:50', hall: halls.red },
        { time: '15:50', hall: halls.red },
        { time: '18:20', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '14:00', hall: halls.green },
        { time: '16:40', hall: halls.green },
        { time: '20:30', hall: halls.green },
        { time: '12:30', hall: halls.blue },
        { time: '13:10', hall: halls.blue },
        { time: '18:30', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '11:00', hall: halls.red },
        { time: '15:20', hall: halls.red },
        { time: '18:50', hall: halls.red },
        { time: '20:00', hall: halls.red },
        { time: '11:10', hall: halls.green },
        { time: '13:50', hall: halls.green },
        { time: '16:20', hall: halls.green },
        { time: '22:10', hall: halls.green },
        { time: '12:30', hall: halls.blue },
        { time: '15:20', hall: halls.blue },
        { time: '17:20', hall: halls.blue },
        { time: '21:30', hall: halls.blue }
      ],
      [
        { time: '12:50', hall: halls.red },
        { time: '14:00', hall: halls.red },
        { time: '18:30', hall: halls.red },
        { time: '21:00', hall: halls.red },
        { time: '11:30', hall: halls.green },
        { time: '14:20', hall: halls.green },
        { time: '18:30', hall: halls.green },
        { time: '21:40', hall: halls.green },
        { time: '11:50', hall: halls.blue },
        { time: '15:50', hall: halls.blue },
        { time: '16:50', hall: halls.blue },
        { time: '22:20', hall: halls.blue }
      ],
      [
        { time: '10:30', hall: halls.red },
        { time: '14:30', hall: halls.red },
        { time: '18:50', hall: halls.red },
        { time: '21:50', hall: halls.red },
        { time: '10:50', hall: halls.green },
        { time: '13:00', hall: halls.green },
        { time: '16:50', hall: halls.green },
        { time: '20:40', hall: halls.green },
        { time: '10:40', hall: halls.blue },
        { time: '15:30', hall: halls.blue },
        { time: '18:40', hall: halls.blue },
        { time: '21:50', hall: halls.blue }
      ],
      [
        { time: '11:50', hall: halls.red },
        { time: '14:40', hall: halls.red },
        { time: '17:50', hall: halls.red },
        { time: '22:50', hall: halls.red },
        { time: '11:50', hall: halls.green },
        { time: '13:50', hall: halls.green },
        { time: '17:00', hall: halls.green },
        { time: '21:10', hall: halls.green },
        { time: '11:40', hall: halls.blue },
        { time: '14:10', hall: halls.blue },
        { time: '17:00', hall: halls.blue },
        { time: '20:40', hall: halls.blue }
      ]
    ]
  }
];
